name: Flutter Web Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for the main branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the permissions for the GITHUB_TOKEN to allow deployment to Pages
permissions:
  contents: read
  pages: write
  id-token: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up the Flutter SDK
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Use the stable channel of Flutter

      # Step 3: Get all the Flutter package dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: YOUR COMMAND - Build the web project with the HTML renderer
      - name: Build Web (HTML Renderer)
        run: flutter build web --web-renderer html

      # Step 5: Optional - Upload the built web files as an artifact.
      # This allows you to download the compiled build from the Actions tab.
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: web_build_output
          path: build/web/
