name: Flutter Web Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0' # Specify a specific version for stability
        channel: 'stable'
        cache: true
        cache-key: flutter-pub-cache
        cache-path: ${{ runner.tool_cache }}/flutter/pub-cache

    - name: Show Flutter version
      run: flutter --version

    - name: Install dependencies
      run: flutter pub get

    - name: Run flutter doctor
      run: flutter doctor -v

    - name: Build web with HTML renderer
      run: flutter build web --web-renderer html --release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web-build-output
        path: build/web/
        retention-days: 7
