name: Deploy to GitHub Pages

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Flutter
      run: |
        cd /tmp
        wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.19.0-stable.tar.xz
        tar xf flutter_linux_3.19.0-stable.tar.xz
        echo "/tmp/flutter/bin" >> $GITHUB_PATH

    - name: Setup and build
      run: |
        flutter config --enable-web
        flutter pub get
        flutter build web --web-renderer html --release

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
