name: Flutter Web Build Test

on:
  workflow_dispatch:

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install basic dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl unzip git

    - name: Download and setup Flutter
      run: |
        cd /tmp
        wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.19.0-stable.tar.xz
        tar xf flutter_linux_3.19.0-stable.tar.xz
        echo "/tmp/flutter/bin" >> $GITHUB_PATH

    - name: Verify Flutter installation
      run: |
        which flutter
        flutter --version
